apiVersion: v1
kind: Pod
metadata:
  name: labels
  # namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: frontend
spec: 
  containers: 
  - name: nginx
    image: nginx


    

