apiVersion: v1
kind: Pod
metadata:
  name: resources-demo

spec: 
  containers:
  - name: nginx
    image: nginx
    resources:
    # soft limit
      requests:
        memory: "65Mi" #RAM IN MB
        cpu: "100m" #CPU 100 milli course
    # hard limit
      limits:
        memory: "128Mi"
        cpu: "150m"