apiVersion: v1
kind: Pod
metadata:
  name: environment-variables
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: project
      value: roboshop
    - name: course
      value: kubernetes
    - name: instructor
      value: vineeth kumar milatai


