apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector: # labels are used for selectors
    project: roboshop
    trainer: vineeth-kumar-milatari
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # target port
