apiVersion: v1
kind: service
metadata: 
  name: nginx-np
spec:
  type: nodeport
  selector:
    project: roboshop
    environment: dev
    component: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80