apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # these labels are replica set
  labels:
    project: roboshop
    purpose: rs-demo
    tier: frontend
    component: frontend
spec:
  replicas: 2
  selector:
  # using these labels replicaset selects the pod
    matchLabels:
      project: roboshop
      purpose: rs-demo
      tier: frontend
      component: frontend
# this is pod definition , pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        purpose: rs-demo
        tier: frontend
        component: frontend

    spec: 
      containers:
      - name: nginx
        image: nginx:stable-trixie-perl 

